export const DUMMY_ITEMS = [
  {
    _id: 'd1',
    title: 'Mystery Bakery Bag',
    description: 'A delicious assortment of day-old breads, pastries, and muffins.',
    originalPrice: 500,
    discountedPrice: 150,
    quantity: 5,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 2 * 60 * 60 * 1000), 
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1000'],
    merchant: { businessName: 'Sweet Tooth Bakery' }
  },
  {
    _id: 'd2',
    title: 'Veg Thali Buffet Leftovers',
    description: 'Fresh and hygienic premium veg thali items packed perfectly.',
    originalPrice: 300,
    discountedPrice: 99,
    quantity: 10,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 1 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1000'],
    merchant: { businessName: 'Annapurna Restaurant' }
  },
  {
    _id: 'd3',
    title: 'Chicken Biryani Deal',
    description: 'Aromatic basmati rice cooked with tender chicken and spices.',
    originalPrice: 350,
    discountedPrice: 150,
    quantity: 3,
    dietaryType: 'Non-Veg',
    expiryTime: new Date(new Date().getTime() + 1.5 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=1000'],
    merchant: { businessName: 'Nawab Biryani' }
  },
  {
    _id: 'd4',
    title: 'Classic Margherita Pizza Slice',
    description: 'Large New York style slices made with fresh mozzarella and basil.',
    originalPrice: 150,
    discountedPrice: 49,
    quantity: 8,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 3 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1513104890d38-7c0f4af42085?q=80&w=1000'],
    merchant: { businessName: 'Pizza Paradise' }
  },
  {
    _id: 'd5',
    title: 'Chicken Tikka Wrap',
    description: 'Spicy chicken tikka wrapped in a fresh roomali roti.',
    originalPrice: 200,
    discountedPrice: 80,
    quantity: 12,
    dietaryType: 'Non-Veg',
    expiryTime: new Date(new Date().getTime() + 4 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1626700051175-6818013e1d4f?q=80&w=1000'],
    merchant: { businessName: 'Wrap Roll' }
  },
  {
    _id: 'd6',
    title: 'Organic Grocery Surplus Bundle',
    description: 'A surprise bundle of organic vegetables and pantry staples.',
    originalPrice: 800,
    discountedPrice: 250,
    quantity: 2,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 5 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1000'],
    merchant: { businessName: 'Whole Foods Market' }
  },
  {
    _id: 'd7',
    title: 'Gourmet Sushi Platter',
    description: 'Assorted sushi rolls made fresh today. Includes salmon and tuna.',
    originalPrice: 1200,
    discountedPrice: 400,
    quantity: 4,
    dietaryType: 'Non-Veg',
    expiryTime: new Date(new Date().getTime() + 1.5 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=1000'],
    merchant: { businessName: 'Sushi Sensation' }
  },
  {
    _id: 'd8',
    title: 'Chocolate Lava Cake',
    description: 'Rich, decadent chocolate lava cakes. Best served warm.',
    originalPrice: 350,
    discountedPrice: 120,
    quantity: 6,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 3.5 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1624353365286-3f8d62daad51?q=80&w=1000'],
    merchant: { businessName: 'Dessert Oasis' }
  },
  {
    _id: 'd13',
    title: 'Mushroom Chowmein',
    description: 'Spicy, wok-tossed noodles with fresh mushrooms and crunchy veggies.',
    originalPrice: 180,
    discountedPrice: 70,
    quantity: 4,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 2 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=1000'], 
    merchant: { businessName: 'Wok Master' }
  },
  {
    _id: 'd14',
    title: 'Crispy Masala Dosa',
    description: 'Authentic South Indian dosa served with hot sambar and fresh coconut chutney.',
    originalPrice: 120,
    discountedPrice: 50,
    quantity: 8,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 1.5 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=1000'], 
    merchant: { businessName: 'South Indian Delights' }
  },
  {
    _id: 'd15',
    title: 'Assorted Cookies Box',
    description: 'Freshly baked chocolate chip, oatmeal, and peanut butter cookies.',
    originalPrice: 300,
    discountedPrice: 120,
    quantity: 5,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 24 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=1000'], 
    merchant: { businessName: 'The Cookie Jar' }
  },
  {
    _id: 'd16',
    title: 'Rice & Yellow Daal Combo',
    description: 'Comforting home-style dal tadka with steamed basmati rice.',
    originalPrice: 150,
    discountedPrice: 60,
    quantity: 10,
    dietaryType: 'Veg',
    expiryTime: new Date(new Date().getTime() + 3 * 60 * 60 * 1000),
    images: ['https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=1000'], 
    merchant: { businessName: 'Maa Ki Rasoi' }
  }
];
